# @package _global_
apply_augmentations: True
random_choice: False
mixed: True
foldlabel: False
trimdepth: False
uniform_trim: False
binary_trim: True
fill_value: 0
max_distance: 100
trimdepth_delta: 141
max_translation: 1
keep_extremity: 'bottom'
percentage: 10
variable_percentage: False
sigma_noise: 0.  # set to positive to allow noise
patch_size: 20
mixed_list: ['trimdepth', 'foldabel', 'cutout'] # give list of augmentations. Applies in following order: foldlabel, cutout, trimdepth