# @package _global_
apply_augmentations: True
random_choice: True
mixed: False
foldlabel: True
trimdepth: True
uniform_trim: False
binary_trim: True
binary_proba_trim: 0.5
fill_value: 0
max_angle: 6
max_distance: 100
trimdepth_delta: 141
max_translation: 1
checkerboard_size: 4
keep_extremity: 'bottom'
percentage: 20
variable_percentage: False
sigma_noise: 0.  # set to positive to allow noise
patch_size: 30
sigma_elastic: 2
size_elastic: 3
proba_trimedges: 0.5
ball_radius: 2
small_patch_size: [7,7,7,1]
nb_patches: 5
vx_crop_edges: 0
ignore_axis_trim: 2
##distribution: [0.2, 0.4, 0.6, 0.8] #equiprobability
##distribution: [0.1667, 0.3333, 0.5, 0.6667, 0.8333] # elastic
##distribution: [0.2, 0.4, 0.6, 0.8, 0.8] # no elastic, equiprobablity
##distribution: [0.2, 0.4, 0.6, 0.8, 0.8, 0.8] # no elastic, #no addbranch, equiprobablity
##distribution: [0.1667, 0.3333, 0.5, 0.6667, 0.8333, 0.8333, 0.8333] # lateral trim # no elastic, #no addbranch, equiprobablity
distribution: [0.,0.2,0.4,0.6,0.6,0.8,0.8,0.8] # BEST : lateral trim # no elastic, #no addbranch, #no foldlabel, equiprobablity
##distribution: [0., 0.25, 0.5, 0.5, 0.75, 0.75, 0.75] # lateral trim # no elastic, #no addbranch, #no foldlabel, #no cutin equiprobablity
#distribution: [0.,0.2,0.6,0.6,0.6,0.8,0.8,0.8] # lateral trim # no elastic, #no addbranch, #no foldlabel, #no cutin, 40% cutout
#distribution: [0.,0.2,0.4,0.4,0.6,0.8,0.8,0.8] # lateral trim # no elastic, #no addbranch, #no foldlabel, #no cutin, multicutout instead
#distribution: [0.,0.1667,0.3333,0.5,0.6667,0.8333,0.8333,0.8333] # all cuts !
#distribution: [0,0,0,0,0] # for translation only
